---
kind: pkgfile.Build
spec:
  targets:
    - kernel
    - kernel-rpi
---
kind: auto.CustomSteps
spec:
  steps:
    - name: kernel-olddefconfig
      toplevel: true
    - name: kernel-%
      toplevel: true
    - name: rpi-kernel-%
      toplevel: true
---
kind: custom.Step
name: kernel-olddefconfig
spec:
  makefile:
    enabled: true
    script:
      - |
        @$(MAKE) local-kernel-build TARGET_ARGS="--build-arg=KERNEL_TARGET=olddefconfig" PLATFORM=linux/amd64 DEST="kernel/build"
        @$(MAKE) local-kernel-build TARGET_ARGS="--build-arg=KERNEL_TARGET=olddefconfig" PLATFORM=linux/arm64 DEST="kernel/build"
---
kind: custom.Step
name: kernel-rpi-bcm2712-defconfig
spec:
  makefile:
    enabled: true
    script:
      - |
        @$(MAKE) local-rpi-kernel-build TARGET_ARGS="--build-arg=KERNEL_TARGET=bcm2712_defconfig" PLATFORM=linux/arm64 DEST="rpi-kernel/build"
---
kind: custom.Step
name: kernel-%
spec:
  makefile:
    enabled: true
    script:
      - |
        for platform in $(shell echo $(PLATFORM) | tr "," " "); do \
          arch=`basename $$platform` ; \
          $(MAKE) docker-kernel-prepare PLATFORM=$$platform TARGET_ARGS="--tag=$(REGISTRY)/$(USERNAME)/kernel:$(TAG)-$$arch --load"; \
          docker run --rm -it --entrypoint=/toolchain/bin/bash -e PATH=/toolchain/bin:/bin -w /src -v $$PWD/kernel/build/config-$$arch:/host/.hostconfig $(REGISTRY)/$(USERNAME)/kernel:$(TAG)-$$arch -c 'cp /host/.hostconfig .config && make $* && cp .config /host/.hostconfig'; \
        done
---
kind: custom.Step
name: rpi-kernel-%
spec:
  makefile:
    enabled: true
    script:
      - |
        for platform in $(shell echo $(PLATFORM) | tr "," " "); do \
          arch=`basename $$platform` ; \
          $(MAKE) docker-rpi-kernel-prepare PLATFORM=$$platform TARGET_ARGS="--tag=$(REGISTRY)/$(USERNAME)/kernel-rpi:$(TAG)-$$arch --load"; \
          docker run --rm -it --entrypoint=/toolchain/bin/bash -e PATH=/toolchain/bin:/bin -w /src -v $$PWD/rpi-kernel/build/config-$$arch:/host/.hostconfig $(REGISTRY)/$(USERNAME)/kernel-rpi:$(TAG)-$$arch -c 'cp /host/.hostconfig .config && make $* && cp .config /host/.hostconfig'; \
        done
