# commit to be tagged for the new release
commit = "HEAD"

project_name = "sbc-turingrk1"
github_repo = "skyssolutions/talos-kernel"
match_deps = "^github.com/(skyssolutions/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
