name: turingrk1-kernel

on:
  push:
    branches: ['main', 'release-*']
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - platform: amd64
            runner: buildjet-16vcpu-ubuntu-2204
          - platform: arm64
            runner: buildjet-16vcpu-ubuntu-2204-arm

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: .github/buildkitd.toml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Harbor registry
        uses: docker/login-action@v3
        with:
          registry: registry.skyssolutions.fi
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build turingrk1 kernel image
        run: make
        env:
          PUSH: '1'
          USERNAME: library
          PLATFORM: linux/${{ matrix.platform }}
          PROGRESS: plain
          CI_ARGS: "--cache-from=registry.skyssolutions.fi/library/talos-kernel:cache-${{ matrix.platform }} --cache-to=registry.skyssolutions.fi/library/talos-kernel:cache-${{ matrix.platform }} --tag=registry.skyssolutions.fi/library/talos-kernel:${{ matrix.platform }}"

  merge:
    runs-on: buildjet-4vcpu-ubuntu-2204
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Harbor registry
        uses: docker/login-action@v3
        with:
          registry: registry.skyssolutions.fi
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Create and push multi-platform image
        run: |
          docker buildx create --use
          docker buildx imagetools create \
            --tag registry.skyssolutions.fi/library/talos-kernel:latest \
            registry.skyssolutions.fi/library/talos-kernel:amd64 \
            registry.skyssolutions.fi/library/talos-kernel:arm64
