name: turingrk1-kernel

on:
  push:
    branches: [ 'main', 'release-*' ]
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - platform: amd64
            runner: buildjet-16vcpu-ubuntu-2204
          - platform: arm64
            runner: buildjet-16vcpu-ubuntu-2204-arm


    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # need history for `git describe` to work for Talos `Makefile`
          fetch-depth: 0
          fetch-tags: true

      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config: .github/buildkitd.toml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build turingrk1 kernel image
        run: make
        env:
          PUSH: '1'
          USERNAME: ${{ github.actor }}
          PLATFORM: linux/${{ matrix.platform }}
          PROGRESS: plain
          CI_ARGS: "--cache-from=ghcr.io/${{ github.actor }}/kernel:cache-${{ matrix.platform }} --cache-to=ghcr.io/${{ github.actor }}/kernel:cache-${{ matrix.platform }} --tag=ghcr.io/${{ github.actor }}/turingrk1-kernel:${{ matrix.platform }} --push=${PUSH}"

  merge:
    runs-on: buildjet-16vcpu-ubuntu-2204-x86
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-platform image
        run: |
          docker buildx create --use
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.actor }}/turingrk1-kernel:latest \
            ghcr.io/${{ github.actor }}/turingrk1-kernel:amd64 \
            ghcr.io/${{ github.actor }}/turingrk1-kernel:arm64
